language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

branches:
  only:
    - master

install:
  - pip install pylint

script:
  - env PYTHONPATH=scripts:${PYTHONPATH} pylint --rcfile ./tests/.pylintrc ./tests/test_simple_calculator.py
  - python tests/test_simple_calculator.py

notifications:
  email:
    recipients:
      - schramm@ucar.edu
    on_success: change # default: change
    on_failure: always # default: always
